services:
    server:
        command: npm run dev
    
    worker:
        ports:
            - '9229:9229' # For node-inspect debugging
        command: npm run dev

    nginx:
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./client/dist:/usr/share/nginx/html

    client-dev:
        container_name: client-dev
        image: node:20-alpine
        working_dir: /app
        command: sh -c "npm install && npm run dev -- --host"
        ports:
            - '5173:5173'
        env_file: ./.env
        volumes:
            - ./client:/app
